# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='nombre', max_length=60)),
                ('descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='nombre', max_length=60)),
                ('email', models.CharField(default='nombre', max_length=60)),
                ('passwd', models.CharField(default='nombre', max_length=60)),
                ('cel', models.CharField(default='nombre', max_length=20)),
                ('phone', models.CharField(default='nombre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='nombre', max_length=60)),
                ('calle', models.CharField(default='nombre', max_length=60)),
                ('ciudad', models.CharField(default='nombre', max_length=60)),
                ('cp', models.CharField(default='nombre', max_length=60)),
                ('pais', models.CharField(default='nombre', max_length=60)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_stock', models.IntegerField()),
                ('cantidad_comprometida', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.CharField(default='nombre', max_length=60)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='nombre', max_length=60)),
                ('nombre', models.CharField(default='nombre', max_length=60)),
                ('descr', models.CharField(default='nombre', max_length=60)),
                ('imagen', models.CharField(default='nombre', max_length=60)),
                ('precio_venta', models.CharField(default='nombre', max_length=60)),
                ('precio_compra', models.CharField(default='nombre', max_length=60)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='nombre', max_length=60)),
                ('email', models.CharField(default='nombre', max_length=60)),
                ('url', models.CharField(default='nombre', max_length=60)),
                ('cel', models.CharField(default='nombre', max_length=60)),
                ('phone', models.CharField(default='nombre', max_length=60)),
                ('Pais', models.CharField(default='nombre', max_length=60)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Status_envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='nombre', max_length=60)),
                ('descr', models.CharField(default='nombre', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='nombre', max_length=60)),
                ('descr', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Proveedor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto'),
        ),
    ]
